version: '3.8'

services:
  backend:
    image: ghcr.io/sudhanshuai/backend:latest  # your repo name instead of sudhanshuai
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres  # your database url
      - REDIS_URL=redis://redis:6379
    ports:
      - "4000:3000"
    depends_on:
      - db
      - redis

  frontend:
    image: ghcr.io/sudhanshuai/frontend:latest  # your repo name instead of sudhanshuai
    environment:
      - NEXT_PUBLIC_BACKEND_BASE_URL=http://backend:3000
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
