name: Docker Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Convert repository owner to lowercase
        id: lowercase_owner
        run: |
          echo "::set-output name=owner::$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')"
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}

      - name: Build and push backend image
        run: |
          docker build -t ghcr.io/${{ steps.lowercase_owner.outputs.owner }}/backend:${{ github.sha }} ./backend
          docker push ghcr.io/${{ steps.lowercase_owner.outputs.owner }}/backend:${{ github.sha }}

  build-and-push-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Convert repository owner to lowercase
        id: lowercase_owner
        run: |
          echo "::set-output name=owner::$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')"
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}

      - name: Build and push frontend image
        run: |
          docker build -t ghcr.io/${{ steps.lowercase_owner.outputs.owner }}/frontend:${{ github.sha }} ./frontend
          docker push ghcr.io/${{ steps.lowercase_owner.outputs.owner }}/frontend:${{ github.sha }}
