name: Docker Build and Publish

on:
  push:
    branches:
      - main  # Modify as per your branch requirements

jobs:
  backend:
    name: Build and Push Backend Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push backend Docker image
        working-directory: ./backend  # Adjust path to your backend Dockerfile
        run: |
          docker build -t ghcr.io/sudhanshuai/backend:${{ github.sha }} .
          docker push ghcr.io/sudhanshuai/backend:${{ github.sha }}

  frontend:
    name: Build and Push Frontend Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push frontend Docker image
        working-directory: ./frontend  # Adjust path to your frontend Dockerfile
        run: |
          docker build -t ghcr.io/sudhanshuai/frontend:${{ github.sha }} .
          docker push ghcr.io/sudhanshuai/frontend:${{ github.sha }}
